# Site Settings
title: Personal Website
url: 'itzsid.github.io'
baseurl: '' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Siddharth Choudhary
tagline: Computer Vision Researcher/Engineer <br> @ Magic Leap
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'I am a Computer Vision Researcher/Engineer (2017-) at <a href="http://magicleap.com">Magic Leap</a>. My primary research interests are in the areas of Robotics and Computer Vision and its intersection with Machine Learning and High Performance Computing. <br><br>
 Before this, I was a PhD candidate (2012-2017) in the <a href="http://sic.gatech.edu">School of Interactive Computing</a>, which is a part of <a href="http://cc.gatech.edu">College of Computing</a> at <a href="http://gatech.edu">Georgia Tech</a>.
I was associated with <a href="http://cogrob.org/">Cognitive Robotics</a> and <a href="http://borg.cc.gatech.edu">BORG</a> lab and I was advised by <a href="http://www.hichristensen.net/">Henrik I. Christensen</a> and <a href="http://frank.dellaert.com">Frank Dellaert</a>. I also collaborated with <a href="http://lucacarlone.com">Luca Carlone</a>, <a href="http://vindelman.net.technion.ac.il/">Vadim Indelman</a>, <a href="http://ajbt.net">Alex Trevor</a>, <a href="https://www.cc.gatech.edu/~cnieto6/">Carlos Nieto</a>, <a href="https://scholar.google.com/citations?user=uH_LDocAAAAJ&hl=en">John Rogers</a> and many others over the course of my PhD. I completed my Bachelors and Masters in Computer Science from <a href="http://iiit.ac.in">IIIT Hyderabad</a> in July 2012 working with <a href="http://iiit.ac.in/~pjn">P J Narayanan</a> at <a href="http://cvit.iiit.ac.in">CVIT</a>.
<br><br>
I have also interned at <a href="http://fyusion.com">Fyusion Inc.</a> and spent some time collaborating with researchers from <a href="https://www.arl.army.mil/www/default.cfm">Army Research Lab</a> which also has funded my research.  
'

#sidebar links
email: itzsid@gmail.com
phone: 404 519 2452 
website: schoudhary.net #do not add http://
linkedin: siddharthchoudhary
github: itzsid
twitter: '@itzsid'
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-35378312-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
